# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TAdManager_iOS_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'TAdManager_iOS', :path => '../'
  pod 'AppLovinSDK', '12.3.1'

  # Pods for TAdManager_iOS_Demo

end
